[project]
name = "project-name"
version = "0.1.0"
description = "Add your description here"
authors = []
dependencies = []
readme = "README.md"
requires-python = ">= 3.12"

[tool.rye]
managed = true
dev-dependencies = [
    "ruff>=0.4.2",
]
